# Generated by Django 3.1.7 on 2021-04-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropLossComm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=11)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cultivation', models.CharField(max_length=255)),
                ('event', models.CharField(choices=[('CE', 'CHUVA EXCESSIVA'), ('GE', 'GEADA'), ('GR', 'GRANIZO'), ('SE', 'SECA'), ('VE', 'VENDAVAL'), ('RA', 'RAIO')], default='CE', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
