# Generated by Django 3.1.7 on 2021-04-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='croplosscomm',
            name='cultivation',
            field=models.ForeignKey(on_delete=models.SET('DELETED'), to='core.cultivation'),
        ),
        migrations.AlterField(
            model_name='croplosscomm',
            name='event',
            field=models.ForeignKey(on_delete=models.SET('DELETED'), to='core.event'),
        ),
    ]
