# Generated by Django 3.1.7 on 2021-04-04 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_croplosscomm_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='croplosscomm',
            name='harvestDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
