# Generated by Django 3.1.7 on 2021-04-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_croplosscomm_harvestdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croplosscomm',
            name='harvestDate',
            field=models.DateField(),
        ),
    ]
