# Generated by Django 3.1.7 on 2021-04-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210404_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croplosscomm',
            name='created',
        ),
        migrations.RemoveField(
            model_name='croplosscomm',
            name='updated',
        ),
    ]
