# Generated by Django 3.1.7 on 2021-04-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210406_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croplosscomm',
            name='cultivation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cultivation'),
        ),
        migrations.AlterField(
            model_name='croplosscomm',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
        migrations.AlterField(
            model_name='croplosscomm',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cultivation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
